# 9. Numpy

Numpy is the package that makes scientific computing in Python possible to begin with. You will probably import in into every script and module you write and if you don't then you're importing a package that depends on `numpy`. It provides important data types like `numpy.arrays`, that are similar to MATLAB arrays. In this notebook we'll focus on this data type.

If you prefer R-style DataFrames, you can go with `pandas`. It's very widely used in Data Science. As stated in the beginning, we won't cover `pandas` here, but you can find a 10 minute intro to pandas [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html) and I sketch out how I would use it for our project in the bonus notebook.

## 9.1 import convention
The convention to import numpy is this:

```Python
import numpy as np
```
You also find
```Python
from numpy import *
```
but I advise against using this approach. Namespaces are a good thing.

In [1]:
import numpy as np

## 9.2 Numpy arrays

The most important aspect of numpy is to provide us with a data type that is able to hold numeric data in an efficient manner. As usual, you can use the class `np.array` as a constructor to transform other data types into numpy arrays.

**Exercise**

Transform the following list of lists into a np.array

In [3]:
data = [[1,0,0],[0,1,0],[0,0,1], [1, 1, 1]];
#your code here


### Indexing

Indexing follows the python principles. I.e. starting at 0 and the end point of a slice is not included. Indices along multiple dimensions are separated by comma.

In [106]:
A = np.reshape(np.arange(1, 26), (5, 5))
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


E.g. to get the center 9 elements:

In [107]:
print(A[1:4, 1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


**Exercise**

Select the last two columns in the first two rows:

In [109]:
# your code here


Here's something that's quite different from MATLAB. In MATLAB, if you only give a single index, you're only going to get a single element. Numpy is different. To understand this, we'll have a look at a two-dimensional array:

In [112]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


The way this is represented shows us the row-dominant order. Arrays are essentially nested lists. Each row is a list. So if you only give one index, you'll get what you would get it you treated them actually as lists of lists: The first list. I.e. the first row:

In [114]:
print(A[0])

[1 2 3 4 5]


Similarly, if you loop over an array, you iterate over the rows. In MATLAB you would get the columns:

In [117]:
for a in A:
    print('Next row:')
    print('\t', a)

Next row:
	 [1 2 3 4 5]
Next row:
	 [ 6  7  8  9 10]
Next row:
	 [11 12 13 14 15]
Next row:
	 [16 17 18 19 20]
Next row:
	 [21 22 23 24 25]


### Create specific arrays

You can use `numpy` functions to create certain arrays that you will need a lot. Typically these are the exact equivalent to the MATLAB function that you're used to. We'll have a look at a few.

#### Random arrays

The `np.random` module contains functions to create pseudorandom arrays. For standard normal or uniform (0-1) random values, you can use `randn` and `rand` respectively. These functions take a variable number of arguments, which are the size of the resulting array. This is how you get a 10 x 2 array of standard normally distributed values:

In [5]:
np.random.rand(10, 2)

array([[0.13328666, 0.71940637],
       [0.00815935, 0.59707787],
       [0.25013322, 0.56001163],
       [0.94926787, 0.09752565],
       [0.18147579, 0.73064491],
       [0.610923  , 0.59280601],
       [0.49973788, 0.90995536],
       [0.51838468, 0.96039533],
       [0.58494641, 0.22446949],
       [0.29519464, 0.84663401]])

**Exercise**

Create a 5x5 array of uniform values between 0 and 1.

In [6]:
# your code here


The `np.random` module also has functions for different distributions, e.g. `beta`, `gamma`, `exponential` and so on. These functions can be fine-tuned by specifiying the parameters of the distribution. In addition they take `size` as an argument. E.g. this is how you get 20x3 values from a `gamma(2, 2)`distribution. Note that you have to give the size as a `tuple`, `list` or something similar.

In [9]:
np.random.gamma(2, 2, size=(20, 3))

array([[ 5.44657009,  7.3883453 ,  8.70843178],
       [ 3.88030444,  1.65327203,  5.59880985],
       [ 1.48768057,  9.64923845,  2.20998367],
       [12.00283979,  1.42280745,  0.16888802],
       [ 2.36063474,  0.81896164,  6.5167027 ],
       [ 0.61841192,  5.86089834,  4.7058251 ],
       [ 3.18395132,  1.91472367,  5.55726116],
       [ 1.07308132,  2.21584325,  0.87622782],
       [ 4.45300943,  1.91004288, 11.33387039],
       [ 3.19175679, 10.99112038,  7.25900382],
       [ 9.53212776,  3.69505993,  4.66865089],
       [ 2.31554035,  5.8827376 ,  2.22029316],
       [ 2.5751989 ,  5.36954558,  1.17894832],
       [ 2.75560411,  4.13622965,  1.60549439],
       [ 0.65126675,  4.0994151 ,  1.37516972],
       [ 4.18033493,  0.29335321,  1.46473547],
       [ 1.09325824,  0.87644133,  4.91018944],
       [ 2.73496152,  6.75028397,  2.91874989],
       [ 2.29933397,  3.01865493,  2.66661814],
       [ 4.43230785,  3.37276678,  3.91790546]])

**Exercise**

Create a 7x1 array of values that are sampled from a `beta(2, 1)` distribution.

In [6]:
# your code here


#### Ones and zeros

These are the same as the respective MATLAB functions. The only difference is that you have to specify the shape as a single argument (e.g. a `tuple`). Just like above:

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Exercise**

Create a 2x2 array of zeros.

In [6]:
# your code here


#### linspace and arange

`linspace` is exactly the same as in MATLAB. `arange` is the equivalent to `1:10`. However, it uses Python logic, i.e. the end value is not included.

In [11]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Exercise**

Create an array of 10 linearly spaced values between 3 and 11:

In [13]:
# your code here


### Shape and dimensions

You can get information about the size and dimensionality of arrays using the `array.size`, `array.shape` and `array.ndim` properties. Properties are dynamically created attributes of an object, kind of like a method except that you don't have to call it using parentheses. Here's a super short example:

In [28]:
class MethodList(list):
    
    def size(self):
        return len(self)
    
    
class PropertyList(list):
    
    @property # this is called a decorator, but that's for a more advanced course
    def size(self):
        return len(self)

Now for the `MethodList` we'd have to call `size` like a method, while we can call it like an attribute for the `PropertyList`.

In [29]:
ml, pl = MethodList([1, 2, 3]), PropertyList([1, 2, 3])

In [30]:
print(ml.size())
print(pl.size)

3
3


Anyway, that's why you don't call them like methods.

 * `array.size` gives you the number of elements (MATLAB: `numel`)
 * `array.shape` gives you the size along the dimensions (MATLAB: `size`)
 * `array.ndim` gives you the dimensionality of an array (e.g. 2 for a 20x3 matrix)

In [31]:
random_matrix = np.random.randn(10, 3)

**Exercise**

Get the size, shape and dimensionality of the random_matrix.

In [119]:
# your code here


### Arithmetics and broadcasting

Adding (or substracting) a scalar (i.e. a single value) or multiplying (or dividing) by a scalar works as expected from MATLAB, i.e. elementwise. Have a look:

In [34]:
a = np.ones(10)
print(a * 4)
print(a + 3.2)

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[4.2 4.2 4.2 4.2 4.2 4.2 4.2 4.2 4.2 4.2]


Exponents also work elementwise (using `**`).

**Exercise**

Turn these values drawn from a standard normal distribution (mean: 0, sd: 1) into values from an IQ distribution (mean: 100, sd: 15):

In [36]:
standard_normal_values = np.random.randn(100)
# your code here


Adding and substracting works differently depending on the shapes of the arrays. If they are the same size, it's just an elementwise operation:

In [52]:
a = np.ones(10) * .5
b = np.linspace(1, 19, 10)
print(a.shape == b.shape)

True


These are the same, shape, so adding and substracting works per element.

In [54]:
print('a:', a)
print('b:', b)
print('a + b:', a + b)
print('a - b:', a - b)

a: [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
b: [ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
a + b: [ 1.5  3.5  5.5  7.5  9.5 11.5 13.5 15.5 17.5 19.5]
a - b: [ -0.5  -2.5  -4.5  -6.5  -8.5 -10.5 -12.5 -14.5 -16.5 -18.5]


Multiplication using the `*`, `**` and `/` operators is also elementwise, i.e. `*` in Python is like `.*` in MATLAB, we'll cover matrix operations in a second.

In [56]:
print('a * b:', a * b)
print('a ** b:', a ** b)

a * b: [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
a ** b: [5.00000000e-01 1.25000000e-01 3.12500000e-02 7.81250000e-03
 1.95312500e-03 4.88281250e-04 1.22070312e-04 3.05175781e-05
 7.62939453e-06 1.90734863e-06]


Things get a bit more complicated with different shapes. This is where **broadcasting** comes in. [Here's](https://numpy.org/doc/stable/user/basics.broadcasting.html) the official description which is quite readable.

Consider the following problem:

In [63]:
a = np.random.randn(10, 1)
b = np.arange(10)
print('a:', a)
print('a:', b)

a: [[ 1.38065187]
 [ 0.70548282]
 [ 0.46295793]
 [ 1.03903561]
 [ 1.07862609]
 [-1.43471705]
 [ 2.28237545]
 [-0.60230134]
 [ 1.77106285]
 [-0.32064508]]
a: [0 1 2 3 4 5 6 7 8 9]


Both are vectors of size 10. But in contrast to MATLAB, there's a difference between a vector of size `(10, 1)` and one of size `(10,)`

In [64]:
print(a.shape, a.ndim)
print(b.shape, b.ndim)
print(a.shape == b.shape)

(10, 1) 2
(10,) 1
False


I.e. until you specify the second dimension, a vector is neither a row nor a column vector. Broadcasting is pretty cool, but the possibility of doing that comes with the cost of potentially unexpected behavior:

In [68]:
print(a + b)
print((a + b).shape)

[[ 1.38065187  2.38065187  3.38065187  4.38065187  5.38065187  6.38065187
   7.38065187  8.38065187  9.38065187 10.38065187]
 [ 0.70548282  1.70548282  2.70548282  3.70548282  4.70548282  5.70548282
   6.70548282  7.70548282  8.70548282  9.70548282]
 [ 0.46295793  1.46295793  2.46295793  3.46295793  4.46295793  5.46295793
   6.46295793  7.46295793  8.46295793  9.46295793]
 [ 1.03903561  2.03903561  3.03903561  4.03903561  5.03903561  6.03903561
   7.03903561  8.03903561  9.03903561 10.03903561]
 [ 1.07862609  2.07862609  3.07862609  4.07862609  5.07862609  6.07862609
   7.07862609  8.07862609  9.07862609 10.07862609]
 [-1.43471705 -0.43471705  0.56528295  1.56528295  2.56528295  3.56528295
   4.56528295  5.56528295  6.56528295  7.56528295]
 [ 2.28237545  3.28237545  4.28237545  5.28237545  6.28237545  7.28237545
   8.28237545  9.28237545 10.28237545 11.28237545]
 [-0.60230134  0.39769866  1.39769866  2.39769866  3.39769866  4.39769866
   5.39769866  6.39769866  7.39769866  8.39769866]


To be completely honest, I think `numpy` should throw an error here and only allow elementwise operations on arrays with the same number of dimensions. If you wanted do perform elementwise operations along a common axis you have a few options (depending on what the desired output is):

 * Add a second dimension to the array with only one dimension. This works with indexing into all available dimensions and then adding a new dimension via `None` or `np.newaxis`.

In [88]:
dim1_array = np.linspace(0, 1, 5)
dim2_array = dim1_array[:, None]
print(dim1_array.shape)
print(dim2_array.shape)

(5,)
(5, 1)


In [89]:
print(b.shape)
print(b[:, None].shape)
print(b[:, np.newaxis].shape)

(10,)
(10, 1)
(10, 1)


With the new singleton dimension, both arrays have the same shape and addition (and so on) work elementwise as expected:

In [82]:
print(a.shape == b[:, None].shape)
print(a + b[:, None])

True
[[1.38065187]
 [1.70548282]
 [2.46295793]
 [4.03903561]
 [5.07862609]
 [3.56528295]
 [8.28237545]
 [6.39769866]
 [9.77106285]
 [8.67935492]]


 * Remove the singleton dimension from `a` 

In [90]:
print(a.shape)
print(a.squeeze().shape)

(10, 1)
(10,)


Without the dimension, the arrays are again of the same shape:

In [85]:
print(a.squeeze().shape == b.shape)
print(a.squeeze() + b)

True
[1.38065187 1.70548282 2.46295793 4.03903561 5.07862609 3.56528295
 8.28237545 6.39769866 9.77106285 8.67935492]


Note that the results in both cases are not the same. One produces a `(10,)` array, the other a `(10, 1)` array. These are different and it's important to be aware of that!

This might seem a bit annoying, but you can use broadcasting to your advantage. Broadcasting basically means that `numpy` is going to attempt to bring different arrays in the same shape by repeating them along singleton dimensions (a `1` in `array.shape`) and then apply elementwise operations. Here's a schematic depiction from the `numpy` documentation:

<img src='../img/broadcasting.png'>


Consider the following three arrays and their shapes:

In [91]:
a = np.random.randn(10, 1, 1)
b = np.random.randn(1, 5, 1)
c = np.random.randn(1, 1, 3)

What do you think is the dimensionality of the result if we add them all? Think about it and when you've made a desicion, run the cell:

In [ ]:
print((a + b + c).shape)

### Fortran vs. C order

This is a potential pitfall, so I'm covering it here.

Fortran and C define different standards about how arrays are stored in memory: [Row-major and column-major order](https://en.wikipedia.org/wiki/Row-_and_column-major_order) respectively. That's basically, when you use `matrix(:)` in MATLAB, do you glue rows together or columns? Fortran and MATLAB are column-dominant. C and numpy are row-dominant.

Have a look:

**Exercise**

   1. Use `np.arange` to create a vector of values from 1 to 25. `np.arange` works like `range()`, except it returns a np.array.
   2. Use the array method `array.reshape()` to reshape it into a `(5, 5)`-matrix. 
   3. What would you expect? Print the array.


In [ ]:
#your code here


The same problem arises for `array.ravel()` and `array.flatten()`, that act similar ([but not identical](https://stackoverflow.com/questions/28930465/what-is-the-difference-between-flatten-and-ravel-functions-in-numpy)). Fortunately, there is a way around this. All of these functions take an optional parameter `order`. You can pass either `'C'`, for row-major order of `'F'` for column-major, Fotran/MATLAB-like order.

**Exercises**

Use `ravel` or `flatten` to reshape the matrix into a vector, using column-major order.

### Stacking and concatenation

To combine arrays you can either concatenate them along an existing axis or stack them (while creating a new axis). Both take an iterable (e.g. a `list`) of arrays and the axis along which to stack or concatenate them. Let's say we have the two following arrays:

In [95]:
A = np.zeros((3, 5))
B = np.ones((3, 5))

Since they have the same shape, we could concatenate them either vertically (MATLAB: `[A; B]`) or horizontally (MATLAB: `[A, B]`). That corresponds to stacking along the first axis (`axis=0` because we start counting at 0 in Python) or the second axis (`axis=1`).

In [97]:
vert = np.concatenate([A, B], axis=0)
horz = np.concatenate([A, B], axis=1)
print(vert.shape)
print(horz.shape)

(6, 5)
(3, 10)


`stack`ing allows us to combine arrays of the same shape along a new dimension. This doesn't have to be the last one!

In [101]:
stack_first_axis = np.stack([A, B], axis=0)
stack_middle_axis = np.stack([A, B], axis=1)
stack_last_axis = np.stack([A, B], axis=2)
print(stack_first_axis.shape)
print(stack_middle_axis.shape)
print(stack_last_axis.shape)

(2, 3, 5)
(3, 2, 5)
(3, 5, 2)


**Exercise**

Assume we have a design matrix `X`. In order to estimate an intercept for a linear regression, we want to add a column of `ones`. Can you do that?

In [104]:
X = np.random.randn(40, 2)
# your code here


### Matrix algebra

The `*`-operator in MATLAB uses matrix multiplication by default. The same operator in Python does not. Python 3.5 introduced the `@`-operator for this purpose. This also shows the meaning of numpy for the Python universe. If you get a new operator for your package, you made it in the Python world.

We'll simulate some data that we would fit with a linear regression. The matrix notation to write the equation for linear regression is this:


$$y=X\beta + \epsilon$$

Which means that `y` can be expressed as a linear combination of the columns of `X`. `X` is the design matrix of size NxK, where N is the number of observations and K is the number of predictors. $\beta$ is the **column vector** of regression weights (i.e. of size Kx1). $\epsilon is a **column vector** of Gaussian noise (i.e. the deviation between the fitted line and the actual data points) which is of size Nx1. Just like `y`.

In MATLAB it could look like this:
```
N = 100;
K = 3;
X = [ones(N, 1), randn(N, K - 1)];
betas = [.3, .5, 1.5]';
epsilon = randn(100, 1) * .3;
y = X * betas + epsilon;
```

**Exercise**

 1. Create a design matrix, starting with a column of ones (you can use the one from the last exercise, that's fine)
 2. Create a column vector `beta` that has as many rows as X has columns.
 3. Create a column vector `epsilon` of random noise with standard deviation 0.3. It should have one column and as many rows as `X`.
 4. Use this arrays to compute `y`.

In [5]:
#your code here


Bonus if you're done early:

The closed-form solution for the betas of a OLS regression is $(X'*X)^{-1}*X'*y$. Try to recover the betas from `X` and `y`. You will need `np.linalg.inv` and for this. You get the transpose of a matrix as `array.T`.

In [7]:
#your code here


# Conclusion

This was barely even scratching the surface. There is **a lot** to be learned about these. But hopefully now you have a rough idea about what you can expect from these packages. In the next notebook we'll still look at descriptive statistics with numpy arrays, but for the data type, that's it!